language: node_js

node_js:
  - "0.12"
  - "iojs-v1.2"
  - "iojs-v1.3"
	- "iojs"
env:
  global:
    - TZ=UTC
    - NODE_ENV=test

script: "make test-cov"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
